### PR TITLE
chore: bump rust version to 1.81.0

### PR DESCRIPTION
**Pull request by j0nl1**

### CODE REVIEW

**Review by chipshort — APPROVED** [review]
Thanks!

**Comment by Freytes** [comment]
The docker image doesnt reflect the newest changes when running: docker pull cosmwasm/optimizer:0.16.0

**Comment by chipshort** [comment]
@Freytes This change has not been released yet as an optimizer version.

**Comment by webmaster128** [comment]
Released as part of 0.16.1 now, have fun everyone

**Pull request merged**
